# Welcome to Jekyll!

# Website settings
title: "SongSong"
description: "Song's blog,use Jekyll and github pages."
keywords: "SJM,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://songjongmun.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Jong Mun, Song'
  first_name: 'Song'
  last_name: 'JongMun'
  email: 'skuugioge@daum.net'
  facebook_username: 'powerioge'
  github_username: 'SongJongMun'
  avatar: 'static/img/landing/profile.JPG'
  desc: 'NHN Entertainment. Rookie-Luna TF'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
  
disqus:
  name: SongJongMun

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
